### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by ethanlindley** [Zaseth/ByteArray.py#1]
Quick question, what version Python is this written in? Would be helpful to other potential contributors if you specified some information as such.

**Comment by Zaseth** [comment]
This is written in Python 2.7.14 but barely maintained.

**Comment by ethanlindley** [comment]
I should've mentioned that my PR was done in Python 3.6.5, though I don't think it should cause any issues being that the code is mostly just a bunch of calculations and such

**Comment by ethanlindley** [comment]
Cool, sounds good
